#!/usr/bin/env bash
# Writes backend/.env for a first deploy.
#
#   bash deploy/make-env.sh
#
# Everything is filled in except OPENROUTER_API_KEY, which you paste yourself so
# it never passes through anyone else's hands. Refuses to overwrite an existing
# .env — a live one holds a secret key that sessions depend on.
#
# The values here are deliberately LOCAL-ONLY: the app is reachable at
# 127.0.0.1:5000 and nowhere else until you choose how to expose it. Email is
# set to dry-run, so nothing is sent while you are still testing.

set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
env_file="$repo/backend/.env"

if [ -e "$env_file" ]; then
  echo "refusing to overwrite $env_file"
  echo "move it aside first if you really want a new one:  mv backend/.env backend/.env.old"
  exit 1
fi

admin_username="${ONTO_ADMIN_USERNAME:-}"
if [ -z "$admin_username" ]; then
  read -rp "Admin username (the account you'll sign up with): " admin_username
fi
[ -n "$admin_username" ] || { echo "admin username is required"; exit 1; }

secret="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"

umask 077
cat > "$env_file" <<EOF
# Generated by deploy/make-env.sh. Never commit this file.

# ── Core ───────────────────────────────────────────────────────────────
ONTO_SECRET_KEY=$secret
ONTO_DB=$repo/onto.db
ONTO_UPLOAD_DIR=$repo/uploads

# Local only for now. Both of these change when you expose the app publicly:
# the URL becomes your real hostname and COOKIE_SECURE goes back to 1.
ONTO_PUBLIC_URL=http://localhost:5000
ONTO_COOKIE_SECURE=0

# ── OpenRouter ─────────────────────────────────────────────────────────
# ↓↓↓ THE ONE LINE YOU MUST FILL IN ↓↓↓
OPENROUTER_API_KEY=
# Starting chain only — re-pick from /admin once you can see what is behaving.
ONTO_MODEL_CHAIN=meta-llama/llama-3.3-70b-instruct:free,google/gemma-2-9b-it:free,mistralai/mistral-7b-instruct:free

# ── Abuse guards ───────────────────────────────────────────────────────
ONTO_SIGNUP_CAP_IP=5
ONTO_DAILY_CAP_USER=300

# ── Admin ──────────────────────────────────────────────────────────────
ONTO_ADMIN_USERNAME=$admin_username

# ── Email ──────────────────────────────────────────────────────────────
# Dry run: emails are printed to the log, never sent. Fill in the Gmail app
# password and set DRY_RUN=0 when you actually want the weekly digests.
ONTO_MAIL_DRY_RUN=1
ONTO_SMTP_HOST=smtp.gmail.com
ONTO_SMTP_PORT=587
ONTO_SMTP_USER=
ONTO_SMTP_PASSWORD=
ONTO_MAIL_FROM=
ONTO_MAIL_FROM_NAME=Onto
ONTO_DEFAULT_TZ=America/New_York

# ── Event discovery ────────────────────────────────────────────────────
# Point this at your self-hosted SearXNG to enable tier-3 LLM research.
ONTO_SEARXNG_URL=
ONTO_CITY=NYC
EOF

chmod 600 "$env_file"
echo "wrote $env_file (mode 600)"
echo
echo "Now paste your OpenRouter key into the OPENROUTER_API_KEY= line:"
echo "    nano $env_file"
